In [1]:
import numpy as np

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: total: 15.6 ms
Wall time: 4.04 ms


In [4]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [5]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [9]:
a == b

array([False,  True, False,  True])

In [10]:
a >= b

array([False,  True,  True,  True])

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [32]:
np.all(a == b)

True

In [18]:
np.all(a == c)

True

In [21]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [28]:
np.exp(b)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [31]:
np.exp(a - b)

array([1., 1., 1., 1., 1.])

In [23]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [26]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [33]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [35]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [38]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [39]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [40]:
x + y

array([1, 2, 3, 4, 5])

In [41]:
x + 1

array([1, 2, 3, 4, 5])

In [62]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [104]:
y = np.arange(5)[:, np.newaxis]
type(y)

numpy.ndarray

In [64]:
x + y 

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [65]:
x * y

array([[ 0,  0,  0],
       [ 1,  2,  3],
       [ 4,  6,  8],
       [ 9, 12, 15],
       [16, 20, 24]])

In [103]:
x = np.array([1, 2, 3, 4])


numpy.ndarray

In [69]:
np.sum(x)

10

In [70]:
x = np.array([1, 3, 2])

In [73]:
x.min()

1

In [75]:
x.max()

3

In [76]:
x.argmin()

0

In [77]:
x.argmax()

1

In [78]:
x = np.array([1, 2, 3, 1])

In [79]:
x.mean()

1.75

In [83]:
np.median(x)

1.5

In [84]:
np.all([True, True, False])

False

In [85]:
np.any([True, True, False])

True

In [86]:
a = np.zeros((100, 100), dtype=np.int)
a

C:\Users\GSENR\AppData\Local\Temp\ipykernel_2896\2477046962.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.zeros((100, 100), dtype=np.int)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [87]:
np.any(a != 0)

False

In [88]:
np.all(a == a)

True

In [90]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [91]:
((a <= b) & (b <= c)).all()

True

In [93]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [94]:
x.sum()

6

In [96]:
x.sum(axis = 0)

array([3, 3])

In [109]:
a = np.arange(30, dtype = 'f').reshape(5,6)
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]], dtype=float32)

In [110]:
a.max()

29.0

In [111]:
a.sum(axis = 1)

array([ 15.,  51.,  87., 123., 159.], dtype=float32)

In [114]:
a.max(axis=1)

array([ 5., 11., 17., 23., 29.], dtype=float32)

In [118]:
a.mean(axis=0)

array([12., 13., 14., 15., 16., 17.], dtype=float32)

In [119]:
a.min(axis=0)

array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [120]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [121]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [122]:
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [123]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [138]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [139]:
a[j]

array([12, 25, 38, 42])

In [127]:
np.sort(a)

array([12, 25, 38, 42])

In [130]:
x = np.array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])

sorting_order = x.argsort(axis=1)[1]
sorting_order

x[:,sorting_order]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [145]:
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
b = np.argsort(a[1])
b
a[:,b]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])