In [2]:
import numpy as np

In [18]:
lis = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
type(ar)

numpy.ndarray

In [20]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for i in data:
    answer.append(i * 2)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [21]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

(a == 2) & (b > 10)

array([False,  True, False])

In [42]:
c = np.array([[0,1,2], [3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
len(c[0])

3

In [51]:
na = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
na

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [57]:
len(na[1])

4

In [61]:
d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])

In [64]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [67]:
len(d), len(d[0]),len(d[0][0])

(2, 3, 4)

In [69]:
d.shape

(2, 3, 4)

In [75]:
a = np.array([0, 1, 2, 3, 4])
a[-2]

3

In [76]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
a[-1, -1]  # 마지막 행의 마지막 열

5

In [82]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
a[:2, :2]  # 첫번째 행 전체

array([[0, 1],
       [4, 5]])

In [93]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [94]:
m[1,2]

7

In [95]:
m[-1:, -1:]

array([[14]])

In [96]:
m[1, 1:3]

array([6, 7])

In [97]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [98]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [101]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [102]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [106]:
a[[0, 2, 4, 6, 8]]

array([11, 33, 55, 77, 99])

In [107]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [113]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [115]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [125]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [126]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [144]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [128]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [139]:
x = np.array([1,2,3,4,5], dtype = 'i')
x[0] + x[3]

5

In [146]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [148]:
x[0] + x[1]

'12'

In [149]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


C:\Users\GSENR\AppData\Local\Temp\ipykernel_10632\1536815541.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\GSENR\AppData\Local\Temp\ipykernel_10632\1536815541.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [150]:
np.log(0)

C:\Users\GSENR\AppData\Local\Temp\ipykernel_10632\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [151]:
np.exp(-np.inf)

0.0

In [169]:
a = np.ones((5,2), dtype = 'f')
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [175]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [179]:
    e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [180]:
f = np.ones_like(b, dtype="f")
f

array([1., 1., 1.], dtype=float32)

In [185]:
g = np.empty([4,3])
g

array([[1.31220511e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 1.12465777e-312, 1.58817677e-052],
       [4.75970758e-090, 1.72129234e+184, 4.29399375e-038],
       [7.78646212e-071, 3.99910963e+252, 1.90979636e-312]])

In [190]:
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
z = np.arange(5,20)
z

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [196]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [200]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [201]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [213]:
b = a.reshape(2,-1,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [216]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [217]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [218]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [219]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [220]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [222]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [223]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [224]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [225]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [230]:
(np.dstack([c1,c2])).shape

(3, 4, 2)

In [231]:
c3 = np.stack([c1,c2])

In [234]:
c3.shape

(2, 3, 4)

In [237]:
np.stack([c1,c2],2)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [238]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [239]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [243]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, (2,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [244]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [258]:
a = np.hstack([np.zeros([3,3]), np.ones([3,2])])
a

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [265]:
b = (np.arange(10, 151, 10)).reshape(3,5)
b

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [268]:
c = np.vstack([a,b])
c

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [281]:
np.tile(c,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [282]:
x = np.arange(3)
x

array([0, 1, 2])

In [283]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [284]:
X,Y = np.meshgrid(x,y)

In [285]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [286]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [288]:
[list(zip(x, y)) for x, y in zip(X, Y)]

TypeError: 'list' object is not callable