In [1]:
import numpy as np

In [36]:
np.random.seed(0)

In [41]:
np.random.rand(10)

array([0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077])

In [45]:
x = np.arange(10)
np.random.shuffle(x)
x

array([1, 2, 0, 7, 5, 6, 8, 3, 4, 9])

In [57]:
np.random.choice(5,10)

array([0, 4, 1, 3, 1, 0, 0, 4, 3, 3])

In [68]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 2, 3, 2, 3, 2, 3, 3, 3])

In [69]:
np.random.rand(10)

array([0.4071833 , 0.069167  , 0.69742877, 0.45354268, 0.7220556 ,
       0.86638233, 0.97552151, 0.85580334, 0.01171408, 0.35997806])

In [73]:
np.random.rand(3,5)

array([[0.23789282, 0.934214  , 0.61396596, 0.5356328 , 0.58990998],
       [0.73012203, 0.311945  , 0.39822106, 0.20984375, 0.18619301],
       [0.94437239, 0.7395508 , 0.49045881, 0.22741463, 0.25435648]])

In [104]:
np.random.randn(10)

array([ 1.00801764,  0.64732911,  1.37639671,  1.35164635, -0.20390633,
        0.56890057, -1.06716754, -1.83073696,  0.40334642,  0.17172238])

In [146]:
np.random.randint(0, 2, size=(100)).mean()

0.48

In [176]:
p = 10000
p

10000

In [179]:
c = np.random.randn(250) * 100
c

array([-8.04152817e+01, -7.25077799e+01, -5.05096878e+01, -7.80357327e-02,
       -1.34974931e+02, -7.47308772e+01,  1.05558301e+02, -1.49641150e+02,
       -1.35775736e+02, -5.22670874e+01,  9.15669175e+01, -2.54933061e+02,
       -1.36534820e+01, -8.71381376e+01, -2.11637145e+02, -5.43317175e+01,
       -9.11068376e+01,  1.55180026e+02,  6.76736065e+01,  7.45187109e+01,
        5.71580985e+01, -6.95754153e+01,  6.91459989e+01, -1.33123557e+02,
       -3.82835626e+01, -1.36792215e+02,  1.80645761e+01,  2.70525914e+01,
       -3.29360411e-02,  4.56013616e+01, -1.81037761e+02,  2.84410047e+01,
        9.54008137e+01, -8.11243453e+01, -6.74917857e+00, -9.71415701e+01,
        2.80418242e+01,  4.81992839e+01, -2.07978154e+01, -2.83881435e+01,
        2.05533334e+01, -1.92404273e+01, -1.04425283e+02, -5.47442952e+01,
       -3.04538936e+01,  1.10110634e+02,  1.15509697e+02, -3.73845667e+00,
       -5.40966615e+01, -5.56535166e+01,  2.10295817e+02,  1.52347513e+02,
       -3.71701580e+01,  

In [180]:
for i in c:
    p = p + i
    print(p)

10029.814413788328
9957.306633903416
9906.796946097566
9906.718910364858
9771.743979837585
9697.013102652587
9802.571403311684
9652.93025373235
9517.15451769335
9464.887430273628
9556.45434774454
9301.521286564901
9287.867804540401
9200.729666925172
8989.0925222689
8934.760804751048
8843.653967106506
8998.833992845386
9066.507599354944
9141.026310277955
9198.184408763836
9128.608993423106
9197.754992322836
9064.63143501403
9026.34787245256
8889.555657934407
8907.620234058637
8934.672825440386
8934.639889399316
8980.241250962634
8799.203490157131
8827.644494870987
8923.04530855257
8841.920963227822
8835.171784660752
8738.030214554792
8766.072038790722
8814.271322707444
8793.473507337145
8765.085363870026
8785.638697241233
8766.398269929265
8661.972986871462
8607.22869166892
8576.774798090128
8686.885432415493
8802.395129773437
8798.65667310471
8744.560011617625
8688.906495024914
8899.202312189807
9051.54982483359
9014.37966680064
9102.285701158266
9209.08607005922
9223.018419970736
9246

In [182]:
np.unique([11, 11, 2, 2, 34, 34]) 

array([ 2, 11, 34])

In [183]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [184]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [185]:
count

array([2, 2, 1], dtype=int64)

In [189]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)